In [3]:
import numpy as np

n = 4
X = np.array(range(1, n + 1))  # X sẽ là np.array([1, 2, 3, 4])
sigma = np.array([4, 3, 2, 1])

def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(sigma) - 1):
        for j in range(i + 1, len(sigma)):
            ket_qua = ket_qua * ((X[i] - X[j]) / (sigma[i] - sigma[j]))
    return ket_qua

sigma = np.array([2, 1, 3, 4])
sgn_by_def(sigma)


np.float64(-1.0)

In [4]:
sigma = np.array([1, 2, 3, 4])
sgn_by_def(sigma)

np.float64(1.0)

In [5]:
sigma = np.array([4, 3, 2, 1])
sgn_by_def(sigma)


np.float64(1.0)

In [7]:
import numpy as np
from itertools import permutations

# Bước 1: Tạo tập hợp các hoán vị Sn
n = 3
X = []
for i in range(1, n + 1):
    X.append(i)

Sn = list(permutations(X))
# print(Sn) # Kết quả: [(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]

# Bước 2: Khởi tạo giá trị ban đầu của định thức.
det = 0

# Bước 3: Xây dựng hàm tính dấu (sgn)
def sgn(p):
    inversions = 0
    p_list = list(p) # Chuyển đổi p thành list để dễ dàng truy cập và so sánh
    n = len(p_list)
    for i in range(n):
        for j in range(i + 1, n):
            if p_list[i] > p_list[j]:
                inversions += 1

    if inversions % 2 == 0:
        return 1
    else:
        return -1

In [8]:
from itertools import permutations
import numpy as np

def sgn_by_def(sigma):
    n = len(sigma)
    count = 0
    for i in range(n):
        for j in range(i+1, n):
            if sigma[i] > sigma[j]:
                count += 1
    return -1 if count % 2 else 1

def phatsinh_dinhthuc(n):
    X = list(range(1, n+1))
    Sn = list(permutations(X))
    dinhthuc = ""
    for sn in Sn:
        sigma = np.array([0]*n)
        product = ""
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product += f"a{i}{sn.index(i)+1}"
        dau = sgn_by_def(sigma)
        product = (" - " if dau != 1 else " + ") + product
        dinhthuc += product
    return dinhthuc

# Test
print("n = 2:", phatsinh_dinhthuc(2))  # a11a22 - a12a21
print("n = 3:", phatsinh_dinhthuc(3))  # Chuỗi biểu diễn khai triển định thức 3x3


n = 2:  + a11a22 - a12a21
n = 3:  + a11a22a33 - a11a23a32 - a12a21a33 + a13a21a32 + a12a23a31 - a13a22a31


In [9]:
import numpy as np
from itertools import permutations
import math

def tinhtoan_dinhthuc(A):
    X = []
    n = int(math.sqrt(A.size))  # Tính kích thước ma trận
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))  # Tập các hoán vị
    dinhthuc = 0
    for sn in Sn:
        sigma = np.array([1])     # Khởi tạo mảng sigma
        sigma.resize([n])
        product = 1
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product *= A[i-1][sn.index(i)]  # Nhân theo chỉ số dòng - cột
        dau = sgn_by_def(sigma)
        if dau != 1:
            product *= -1
        dinhthuc += product
    return dinhthuc


In [10]:
matran = np.array([
    [3, 5, -8],
    [4, 12, -1],
    [2, 5, 3]
])

print("Giá trị định thức:", tinhtoan_dinhthuc(matran))


Giá trị định thức: 85


In [14]:
import numpy as np
A = np.array([[4, -2],[3, -5]]) # khai báo ma trận A
A1 = np.array([[10, -2],[11, -5]])
A2 = np.array([[4, 10],[3, 11]])
from scipy import linalg
detA = linalg.det(A) # tính định thức cho ma trận A
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)
print(detA,detA1,detA2)

-14.0 -28.0 14.000000000000004


In [16]:
if (detA != 0):
    x1 = detA1 / detA
    x2 = detA2 / detA
    print ("Hai nghiệm của phương trình là: ", x1, x2)
def tinhtoan_dinhthuc(matrix):
    return linalg.det(matrix)

# Gọi hàm cho các ma trận A, A1, A2
print("Định thức của A bằng hàm tinhtoan_dinhthuc:", tinhtoan_dinhthuc(A))
print("Định thức của A1 bằng hàm tinhtoan_dinhthuc:", tinhtoan_dinhthuc(A1))
print("Định thức của A2 bằng hàm tinhtoan_dinhthuc:", tinhtoan_dinhthuc(A2))

Hai nghiệm của phương trình là:  2.0 -1.0000000000000002
Định thức của A bằng hàm tinhtoan_dinhthuc: -14.0
Định thức của A1 bằng hàm tinhtoan_dinhthuc: -28.0
Định thức của A2 bằng hàm tinhtoan_dinhthuc: 14.000000000000004


In [19]:
import numpy as np

# Ma trận hệ số A và vector hệ số tự do B
A = np.array([[-1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])

B = np.array([1, 3, 2])
from scipy.linalg import solve

nghiem = solve(A, B)
print("Nghiệm của hệ phương trình (dùng scipy):", nghiem)



Nghiệm của hệ phương trình (dùng scipy): [ 1.   -1.25 -1.5 ]


<ipython-input-19-1152284133>:11: LinAlgWarning: Ill-conditioned matrix (rcond=1.00929e-17): result may not be accurate.
  nghiem = solve(A, B)


In [20]:

# Tính định thức của ma trận A
det_A = tinhtoan_dinhthuc(A)

# Tạo các ma trận thay cột và tính định thức
A1 = A.copy()
A1[:, 0] = B
det_A1 = tinhtoan_dinhthuc(A1)

A2 = A.copy()
A2[:, 1] = B
det_A2 = tinhtoan_dinhthuc(A2)

A3 = A.copy()
A3[:, 2] = B
det_A3 = tinhtoan_dinhthuc(A3)

# Áp dụng định lý Cramer:
x = det_A1 / det_A
y = det_A2 / det_A
z = det_A3 / det_A

print("Nghiệm của hệ phương trình (Cramer):", (x, y, z))


Nghiệm của hệ phương trình (Cramer): (np.float64(nan), np.float64(nan), np.float64(nan))


<ipython-input-20-2348843397>:18: RuntimeWarning: invalid value encountered in scalar divide
  x = det_A1 / det_A
<ipython-input-20-2348843397>:19: RuntimeWarning: invalid value encountered in scalar divide
  y = det_A2 / det_A
<ipython-input-20-2348843397>:20: RuntimeWarning: invalid value encountered in scalar divide
  z = det_A3 / det_A


In [22]:
from scipy.linalg import det
import numpy as np

A = np.array([[-1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])

B = np.array([1, 3, 2])

# Tạo các ma trận thay cột theo định lý Cramer
A_x = A.copy()
A_x[:, 0] = B

A_y = A.copy()
A_y[:, 1] = B

A_z = A.copy()
A_z[:, 2] = B

# Tính định thức
detA = det(A)
detX = det(A_x)
detY = det(A_y)
detZ = det(A_z)

# Tính nghiệm
x, y, z = detX/detA, detY/detA, detZ/detA

print("Nghiệm của phương trình: ", "x =", x, ", y =", y, ", z =", z)


Nghiệm của phương trình:  x = nan , y = nan , z = nan


<ipython-input-22-3964995896>:27: RuntimeWarning: invalid value encountered in scalar divide
  x, y, z = detX/detA, detY/detA, detZ/detA


In [23]:
import numpy as np

A = np.array([[-1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])

B = np.array([1, 3, 2])

A_x = A.copy()
A_x[:, 0] = B

A_y = A.copy()
A_y[:, 1] = B

A_z = A.copy()
A_z[:, 2] = B

det = tinhtoan_dinhthuc(A)
detX = tinhtoan_dinhthuc(A_x)
detY = tinhtoan_dinhthuc(A_y)
detZ = tinhtoan_dinhthuc(A_z)

x, y, z = detX/det, detY/det, detZ/det  # tính toán x, y, z

print("Nghiệm", "x=", x, "y=", y, "z =", z)


Nghiệm x= nan y= nan z = nan


<ipython-input-23-4277014241>:23: RuntimeWarning: invalid value encountered in scalar divide
  x, y, z = detX/det, detY/det, detZ/det  # tính toán x, y, z


In [24]:
#Tính diện tích tam giác:
import sympy as sp
TG = sp.Matrix ([[1, 0, 1],[4, 3, 1],[2 ,2, 1]])
1/2*TG.det()


1.50000000000000

In [30]:
#Ứng dụng 1
polygon = [
    (1181128.25, 603263.70),  # Điểm 1
    (1181136.18, 603266.68),  # Điểm 2
    (1181130.97, 603279.69),  # Điểm 3
    (1181125.77, 603281.91),  # Điểm 4
    (1181122.06, 603280.42)   # Điểm 5
]

#Tính diện tích đa giác với tọa độ 5 điểm từ bảng
def tinh_dien_tich(polygon):
    n = len(polygon)
    area = 0
    for i in range(n):
        x1, y1 = polygon[i]
        x2, y2 = polygon[(i + 1) % n]  # Đảm bảo vòng lại điểm đầu
        area += (x1 * y2 - x2 * y1)
    return abs(area) / 2

In [32]:
dien_tich = tinh_dien_tich(polygon)
print("Diện tích đa giác là:", dien_tich, "m²")
print("Diện tích (ha):", dien_tich / 10_000)


Diện tích đa giác là: 139.56793212890625 m²
Diện tích (ha): 0.013956793212890626


In [33]:
#Ứng dụng 2
from sympy import Matrix

# Tạo ma trận 4x4 với cột cuối là 1
M = Matrix([
    [0, 4, 1, 1],   # Điểm A
    [4, 0, 0, 1],   # Điểm B
    [3, 5, 2, 1],   # Điểm C
    [2, 2, 5, 1]    # Điểm D
])

# Tính thể tích: 1/6 * |det(M)|
the_tich = abs(M.det()) / 6

print("Thể tích của tứ diện là:", the_tich)


Thể tích của tứ diện là: 12


In [35]:
#Ứng dụng 3
import numpy as np

def are_four_points_coplanar(p1, p2, p3, p4, tolerance=1e-9):
    # Chuyển các điểm thành mảng numpy để dễ tính toán vector
    p1 = np.array(p1)
    p2 = np.array(p2)
    p3 = np.array(p3)
    p4 = np.array(p4)

    # Tạo ba vector từ một điểm chung (ví dụ: p1)
    # v1 = vector từ p1 đến p2
    # v2 = vector từ p1 đến p3
    # v3 = vector từ p1 đến p4
    v1 = p2 - p1
    v2 = p3 - p1
    v3 = p4 - p1

    # Tính tích hỗn tạp của ba vector này
    # Tích hỗn tạp (v1 x v2) . v3
    # Đây cũng chính là định thức của ma trận có các hàng (hoặc cột) là các vector này
    # Giá trị tuyệt đối của tích hỗn tạp chia cho 6 là thể tích tứ diện
    # Nếu 4 điểm đồng phẳng, thể tích tứ diện bằng 0, tức là tích hỗn tạp bằng 0.
    scalar_triple_product = np.dot(np.cross(v1, v2), v3)

    # Kiểm tra xem tích hỗn tạp có gần bằng 0 hay không
    return abs(scalar_triple_product) < tolerance

# Ví dụ sử dụng:

# Ví dụ 1: 4 điểm đồng phẳng (trên mặt phẳng z=0)
point1 = [0, 0, 0]
point2 = [1, 0, 0]
point3 = [0, 1, 0]
point4 = [1, 1, 0]
print(f"Điểm 1: {point1}, Điểm 2: {point2}, Điểm 3: {point3}, Điểm 4: {point4}")
if are_four_points_coplanar(point1, point2, point3, point4):
    print("Bốn điểm này đồng phẳng.")
else:
    print("Bốn điểm này không đồng phẳng.")

# Ví dụ 2: 4 điểm không đồng phẳng (tạo thành một tứ diện)
point_a = [0, 0, 0]
point_b = [1, 0, 0]
point_c = [0, 1, 0]
point_d = [0, 0, 1] # Điểm này không nằm trên mặt phẳng xy
print(f"\nĐiểm A: {point_a}, Điểm B: {point_b}, Điểm C: {point_c}, Điểm D: {point_d}")
if are_four_points_coplanar(point_a, point_b, point_c, point_d):
    print("Bốn điểm này đồng phẳng.")
else:
    print("Bốn điểm này không đồng phẳng.")

# Ví dụ 3: Các điểm gần đồng phẳng với tolerance
point_e = [0, 0, 0]
point_f = [1, 0, 0]
point_g = [0, 1, 0]
point_h = [0, 0, 0.0000000001] # Rất gần mặt phẳng
print(f"\nĐiểm E: {point_e}, Điểm F: {point_f}, Điểm G: {point_g}, Điểm H: {point_h}")
if are_four_points_coplanar(point_e, point_f, point_g, point_h):
    print("Bốn điểm này đồng phẳng (trong giới hạn sai số).")
else:
    print("Bốn điểm này không đồng phẳng.")

# Ví dụ 4: Các điểm không đồng phẳng
point_i = [0, 0, 0]
point_j = [1, 2, 3]
point_k = [4, 5, 6]
point_l = [7, 8, 10] # Khác một chút so với 7,8,9 (đồng phẳng)
print(f"\nĐiểm I: {point_i}, Điểm J: {point_j}, Điểm K: {point_k}, Điểm L: {point_l}")
if are_four_points_coplanar(point_i, point_j, point_k, point_l):
    print("Bốn điểm này đồng phẳng.")
else:
    print("Bốn điểm này không đồng phẳng.")

Điểm 1: [0, 0, 0], Điểm 2: [1, 0, 0], Điểm 3: [0, 1, 0], Điểm 4: [1, 1, 0]
Bốn điểm này đồng phẳng.

Điểm A: [0, 0, 0], Điểm B: [1, 0, 0], Điểm C: [0, 1, 0], Điểm D: [0, 0, 1]
Bốn điểm này không đồng phẳng.

Điểm E: [0, 0, 0], Điểm F: [1, 0, 0], Điểm G: [0, 1, 0], Điểm H: [0, 0, 1e-10]
Bốn điểm này đồng phẳng (trong giới hạn sai số).

Điểm I: [0, 0, 0], Điểm J: [1, 2, 3], Điểm K: [4, 5, 6], Điểm L: [7, 8, 10]
Bốn điểm này không đồng phẳng.


In [37]:
#Ứng dụng 4
from sympy import symbols, Matrix
x, y, z = symbols('x y z')
P1 = [-1, 3, 2]
P2 = [0, 1, 0]
P3 = [-2, 0, 1]

MP = Matrix([
    [x, y, z, 1],
    [P1[0], P1[1], P1[2], 1],
    [P2[0], P2[1], P2[2], 1],
    [P3[0], P3[1], P3[2], 1]
])

print("Ma trận MP:")
print(MP)

equation_of_plane = MP.det()

print("\nPhương trình mặt phẳng:")
print(f"{equation_of_plane} = 0")

Ma trận MP:
Matrix([[x, y, z, 1], [-1, 3, 2, 1], [0, 1, 0, 1], [-2, 0, 1, 1]])

Phương trình mặt phẳng:
-4*x + 3*y - 5*z - 3 = 0


In [39]:
from sympy import symbols, Matrix

def find_ellipse_equation_from_five_points(points):
    if len(points) != 5:
        print("Cần chính xác 5 điểm để xác định một hình elip.")
        return None

    # Khai báo các biến tượng trưng x, y
    x, y = symbols('x y')

    # Xây dựng các hàng của ma trận
    # Hàng đầu tiên chứa các biến tượng trưng: [x^2, xy, y^2, x, y, 1]
    matrix_rows = [[x**2, x*y, y**2, x, y, 1]]

    # Thêm các hàng cho 5 điểm cố định
    for px, py in points:
        matrix_rows.append([px**2, px*py, py**2, px, py, 1])

    # Tạo ma trận Sympy
    M = Matrix(matrix_rows)

    print("Ma trận để tính định thức:")
    print(M)

    # Tính định thức của ma trận
    # Phương trình elip là định thức này bằng 0
    ellipse_equation = M.det()

    return ellipse_equation

# Ví dụ sử dụng:
# Để minh họa, tôi sẽ chọn 5 điểm sao cho chúng tạo thành một hình elip đơn giản hoặc một đường tròn
# Ví dụ: 5 điểm trên một đường tròn x^2 + y^2 = 25 (tâm (0,0), bán kính 5)
# (5,0), (0,5), (-5,0), (0,-5), (3,4)
# Nếu là đường tròn thì phương trình sẽ có dạng x^2 + y^2 - R^2 = 0, tức là a=1, c=1, d=0, e=0, f=-R^2, b=0
# Các điểm ví dụ:
sample_points = [
    (5, 0),
    (0, 5),
    (-5, 0),
    (0, -5),
    (3, 4)
]

print(f"Các điểm được sử dụng: {sample_points}\n")

ellipse_eq = find_ellipse_equation_from_five_points(sample_points)

if ellipse_eq is not None:
    print("\nPhương trình của hình elip đi qua 5 điểm là:")
    print(f"{ellipse_eq} = 0")

    # Để kiểm tra, chúng ta có thể thay một điểm vào phương trình
    # Ví dụ: Thay điểm (5, 0) vào phương trình
    x_val = 5
    y_val = 0
    # Sử dụng .subs() để thay thế các biến
    result_at_point = ellipse_eq.subs({x: x_val, y: y_val})
    print(f"\nKiểm tra phương trình tại điểm ({x_val}, {y_val}): {result_at_point}")
    # Nếu kết quả là 0, điều đó xác nhận điểm đó nằm trên elip.
    # Trong trường hợp này, sympy đã tính toán chính xác, nên nó sẽ là 0.

    # Một ví dụ khác với 5 điểm không nhất thiết tạo thành đường tròn đơn giản
    # Đây là các điểm bất kỳ
    random_points = [
        (1, 2),
        (-3, 1),
        (0, -4),
        (2, 0),
        (-1, -1)
    ]
    print(f"\n--- Ví dụ với 5 điểm bất kỳ: {random_points} ---")
    ellipse_eq_random = find_ellipse_equation_from_five_points(random_points)
    if ellipse_eq_random is not None:
        print("\nPhương trình của hình elip đi qua 5 điểm bất kỳ là:")
        print(f"{ellipse_eq_random} = 0")

Các điểm được sử dụng: [(5, 0), (0, 5), (-5, 0), (0, -5), (3, 4)]

Ma trận để tính định thức:
Matrix([[x**2, x*y, y**2, x, y, 1], [25, 0, 0, 5, 0, 1], [0, 0, 25, 0, 5, 1], [25, 0, 0, -5, 0, 1], [0, 0, 25, 0, -5, 1], [9, 12, 16, 3, 4, 1]])

Phương trình của hình elip đi qua 5 điểm là:
-30000*x**2 - 30000*y**2 + 750000 = 0

Kiểm tra phương trình tại điểm (5, 0): 0

--- Ví dụ với 5 điểm bất kỳ: [(1, 2), (-3, 1), (0, -4), (2, 0), (-1, -1)] ---
Ma trận để tính định thức:
Matrix([[x**2, x*y, y**2, x, y, 1], [1, 2, 4, 1, 2, 1], [9, -3, 1, -3, 1, 1], [0, 0, 16, 0, -4, 1], [4, 0, 0, 2, 0, 1], [1, 1, 1, -1, -1, 1]])

Phương trình của hình elip đi qua 5 điểm bất kỳ là:
888*x**2 + 1604*x*y - 160*x + 76*y**2 - 504*y - 3232 = 0


In [43]:
#BÀI TẬP CHƯƠNG 4
#Câu 1
import numpy as np

def get_minor_matrix(matrix, i, j):

    return np.delete(np.delete(matrix, i, axis=0), j, axis=1)

def get_cofactor_matrix(matrix):
    n = matrix.shape[0]
    if n != matrix.shape[1]:
        raise ValueError("Ma trận phải là ma trận vuông để tính ma trận hệ số kép.")

    cofactor_matrix = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            minor = get_minor_matrix(matrix, i, j)
            # Tính định thức của ma trận con
            det_minor = np.linalg.det(minor)
            # Tính hệ số kép
            cofactor = ((-1)**(i + j)) * det_minor
            cofactor_matrix[i, j] = cofactor
    return cofactor_matrix

def get_adjoint_matrix(matrix):
    cofactor_matrix = get_cofactor_matrix(matrix)
    adjoint_matrix = cofactor_matrix.T  # Chuyển vị
    return adjoint_matrix

# --- Ví dụ sử dụng ---
print("--- Câu 1: Tính ma trận hệ số kép và ma trận liên hợp ---")

# Ví dụ 1: Ma trận 2x2
A_2x2 = np.array([
    [1, 2],
    [3, 4]
])
print("\nMa trận A (2x2):\n", A_2x2)

cofactor_A_2x2 = get_cofactor_matrix(A_2x2)
print("Ma trận hệ số kép của A (2x2):\n", cofactor_A_2x2)

adjoint_A_2x2 = get_adjoint_matrix(A_2x2)
print("Ma trận liên hợp của A (2x2):\n", adjoint_A_2x2)

# Ví dụ 2: Ma trận 3x3
A_3x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\nMa trận A (3x3):\n", A_3x3)

cofactor_A_3x3 = get_cofactor_matrix(A_3x3)
print("Ma trận hệ số kép của A (3x3):\n", cofactor_A_3x3)

adjoint_A_3x3 = get_adjoint_matrix(A_3x3)
print("Ma trận liên hợp của A (3x3):\n", adjoint_A_3x3)

# Ví dụ 3: Ma trận 3x3 khác (có định thức khác 0 để có thể tính nghịch đảo)
A_3x3_det_nonzero = np.array([
    [1, 0, 2],
    [0, 1, 0],
    [-1, 1, 1]
])
print("\nMa trận A (3x3, định thức khác 0):\n", A_3x3_det_nonzero)

cofactor_A_3x3_det_nonzero = get_cofactor_matrix(A_3x3_det_nonzero)
print("Ma trận hệ số kép của A (3x3, định thức khác 0):\n", cofactor_A_3x3_det_nonzero)

adjoint_A_3x3_det_nonzero = get_adjoint_matrix(A_3x3_det_nonzero)
print("Ma trận liên hợp của A (3x3, định thức khác 0):\n", adjoint_A_3x3_det_nonzero)

# Kiểm tra mối quan hệ A * adj(A) = det(A) * I
det_A_3x3_det_nonzero = np.linalg.det(A_3x3_det_nonzero)
print(f"\nĐịnh thức của A (3x3, định thức khác 0): {det_A_3x3_det_nonzero}")
product_A_adj = np.dot(A_3x3_det_nonzero, adjoint_A_3x3_det_nonzero)
print("A * adj(A):\n", product_A_adj)
identity_matrix = np.eye(A_3x3_det_nonzero.shape[0]) * det_A_3x3_det_nonzero
print("det(A) * I:\n", identity_matrix)

--- Câu 1: Tính ma trận hệ số kép và ma trận liên hợp ---

Ma trận A (2x2):
 [[1 2]
 [3 4]]
Ma trận hệ số kép của A (2x2):
 [[ 4. -3.]
 [-2.  1.]]
Ma trận liên hợp của A (2x2):
 [[ 4. -2.]
 [-3.  1.]]

Ma trận A (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Ma trận hệ số kép của A (3x3):
 [[ -3.   6.  -3.]
 [  6. -12.   6.]
 [ -3.   6.  -3.]]
Ma trận liên hợp của A (3x3):
 [[ -3.   6.  -3.]
 [  6. -12.   6.]
 [ -3.   6.  -3.]]

Ma trận A (3x3, định thức khác 0):
 [[ 1  0  2]
 [ 0  1  0]
 [-1  1  1]]
Ma trận hệ số kép của A (3x3, định thức khác 0):
 [[ 1. -0.  1.]
 [ 2.  3. -1.]
 [-2. -0.  1.]]
Ma trận liên hợp của A (3x3, định thức khác 0):
 [[ 1.  2. -2.]
 [-0.  3. -0.]
 [ 1. -1.  1.]]

Định thức của A (3x3, định thức khác 0): 3.0000000000000004
A * adj(A):
 [[3.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 3.0000000e+00 0.0000000e+00]
 [0.0000000e+00 4.4408921e-16 3.0000000e+00]]
det(A) * I:
 [[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


In [44]:
#Câu 2
from sympy import symbols, Matrix, sqrt

def find_circle_equation_from_three_points(points):

    if len(points) != 3:
        print("Cần chính xác 3 điểm để xác định một đường tròn.")
        return None

    # Khai báo các biến tượng trưng x, y
    x, y = symbols('x y')

    # Xây dựng các hàng của ma trận
    # Hàng đầu tiên chứa các biến tượng trưng: [x^2 + y^2, x, y, 1]
    matrix_rows = [[x**2 + y**2, x, y, 1]]

    # Thêm các hàng cho 3 điểm cố định
    for px, py in points:
        matrix_rows.append([px**2 + py**2, px, py, 1])

    # Tạo ma trận Sympy
    M = Matrix(matrix_rows)

    print("Ma trận để tính định thức cho phương trình đường tròn:")
    print(M)

    # Tính định thức của ma trận
    # Phương trình đường tròn là định thức này bằng 0
    circle_equation = M.det()


    if circle_equation != 0:
        expanded_eq = circle_equation.expand()

        # Hệ số của x^2 và y^2 phải bằng nhau trong phương trình đường tròn
        coeff_x2 = expanded_eq.coeff(x**2)
        coeff_y2 = expanded_eq.coeff(y**2)
        coeff_xy = expanded_eq.coeff(x*y) # Phải là 0 cho đường tròn

        if coeff_xy != 0:
            print("Cảnh báo: Biểu thức có chứa hạng tử xy, có thể không phải là đường tròn thuần túy.")
            print("Đây có thể là lỗi nếu các điểm thẳng hàng hoặc định thức trả về 0.")

        # Lấy các hệ số của x, y và hằng số
        coeff_x = expanded_eq.coeff(x)
        coeff_y = expanded_eq.coeff(y)
        coeff_const = expanded_eq.coeff(1) # Hằng số tự do

        # Tìm ước chung lớn nhất (GCD) của các hệ số (nếu là số nguyên)
        # Bao gồm cả coeff_x2 và coeff_y2 (chúng phải giống nhau)
        coeffs_list = [coeff_x2, coeff_x, coeff_y, coeff_const]

        from fractions import Fraction
        # Chuyển đổi các hệ số thành phân số để tìm GCD của tử số và LCM của mẫu số
        # Đây là một cách phức tạp hơn để xử lý số thập phân hoặc phân số từ định thức

        # Đơn giản hơn, nếu các hệ số là số nguyên (như thường lệ với dữ liệu điểm nguyên),
        # ta có thể tìm GCD của giá trị tuyệt đối của chúng.
        if all(c.is_Integer for c in coeffs_list):
            from math import gcd
            # Khởi tạo GCD với giá trị tuyệt đối của hệ số đầu tiên không bằng 0
            # Hoặc chỉ đơn giản là tất cả các hệ số
            current_gcd = 0
            for c in coeffs_list:
                current_gcd = gcd(current_gcd, int(abs(c)))

            if current_gcd > 1:
                circle_equation = circle_equation / current_gcd
                print(f"\nĐã chia phương trình cho ước chung lớn nhất: {int(current_gcd)}")

    return circle_equation

