<a href="https://colab.research.google.com/github/huvimal/DSTT/blob/main/ThiDSTT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

#Câu 1: Phép toán cơ bản trên vector và ma trận
# Cho 2 vector A, B và ma trận C
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, 1, 4],
              [-1, 3, -2],
              [0, 2, 5]])

# a) Tính tổng A + B và tích số 2A + 3B.
sum_AB = A + B
print(f"A + B = {sum_AB}")

scaled_sum_AB = 2 * A + 3 * B
print(f"2A + 3B = {scaled_sum_AB}")

# b) Tính tích vô hướng A · B và góc giữa hai vector (tính bằng độ, làm tròn đến 3 chữ số thập phân).
dot_product_AB = np.dot(A, B)
print(f"A · B = {dot_product_AB}")

norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)

# Tránh chia cho 0 nếu một trong các vector là vector 0
if norm_A == 0 or norm_B == 0:
    angle_rad = 0
else:
    cos_theta = dot_product_AB / (norm_A * norm_B)
    # Đảm bảo cos_theta nằm trong khoảng [-1, 1] để tránh lỗi arccos do lỗi số học
    cos_theta = np.clip(cos_theta, -1.0, 1.0)
    angle_rad = np.arccos(cos_theta)

angle_deg = np.degrees(angle_rad)
print(f"Góc giữa A và B = {angle_deg:.3f} độ")

# c) Tính tích ma trận CCT (ma trận C nhân với chuyển vị của nó).
C_transpose = C.T
C_CT = np.dot(C, C_transpose)
print(f"CCT = \n{C_CT}")

print("\n" + "="*70 + "\n")



A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]
A · B = -5
Góc giữa A và B = 99.594 độ
CCT = 
[[21 -7 22]
 [-7 14 -4]
 [22 -4 29]]




In [4]:
#Câu 2: Nhân ma trận, định thức và hạng ma trận
# Cho ma trận M và N
M = np.array([[2, -1, 3, 0],
              [1, 4, -2, 5],
              [0, 2, 6, -3],
              [-1, 0, 1, 4]])

N = np.array([[1, 3, -2, 0],
              [4, -1, 5, 2],
              [0, 2, 3, -1],
              [-3, 1, 0, 4]])

# a) Tính tích ma trận M × N.
product_MN = np.dot(M, N)
print(f"M × N = \n{product_MN}")

# b) Tính định thức của ma trận M. Nếu không khả thi, giải thích lý do.
# Ma trận M là ma trận vuông (4x4), do đó có thể tính định thức.
determinant_M = np.linalg.det(M)
print(f"Định thức của M = {determinant_M:.3f}")

# c) Tính hạng của ma trận N.
print("\nc) Hạng của ma trận N:")
rank_N = np.linalg.matrix_rank(N)
print(f"Hạng của ma trận N = {rank_N}")

print("\n" + "="*70 + "\n")



M × N = 
[[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
Định thức của M = 409.000

c) Hạng của ma trận N:
Hạng của ma trận N = 4




In [5]:
#Câu 3: Nghịch đảo ma trận và giải hệ phương trình

# Cho ma trận P
P = np.array([[3, -1, 0, 2],
              [0, 1, 5, -1],
              [1, 4, -2, 0],
              [2, 0, 1, 3]])

# Ma trận hệ số A_sys và vector hằng số b_sys của hệ phương trình
A_sys = np.array([[3, -1, 0, 2],
                  [0, 1, 5, -1],
                  [0, 0, 4, -2],  # Giả định: 4z - 2w = 8
                  [2, 0, 1, 3]])
b_sys = np.array([6, 3, 8, 7])


# a) Tìm ma trận nghịch đảo của P. Nếu không khả nghịch, giải thích lý do.
# Kiểm tra định thức của P để xem P có khả nghịch không
det_P = np.linalg.det(P)
print(f"Định thức của P = {det_P:.3f}")

if det_P == 0:
    print("Ma trận P không khả nghịch vì định thức của nó bằng 0.")
else:
    P_inv = np.linalg.inv(P)
    print(f"Ma trận nghịch đảo của P = \n{P_inv}")

# b) Giải hệ phương trình trên bằng cách sử dụng nghịch đảo ma trận.
# Trước tiên, cần đảm bảo A_sys là ma trận vuông và khả nghịch
det_A_sys = np.linalg.det(A_sys)
print(f"Định thức của ma trận hệ số A_sys = {det_A_sys:.3f}")

if det_A_sys == 0:
    print("Ma trận hệ số A_sys không khả nghịch, không thể giải hệ phương trình bằng phương pháp nghịch đảo ma trận.")
else:
    A_sys_inv = np.linalg.inv(A_sys)
    solution_x = np.dot(A_sys_inv, b_sys)
    print(f"Nghiệm của hệ phương trình (x, y, z, w) = {solution_x}")

# c) Kiểm tra nghiệm bằng cách nhân ma trận P với vector nghiệm và so sánh với vector hằng số.
if det_A_sys != 0:
    check_result = np.dot(A_sys, solution_x)
    print(f"A_sys * solution_x = {check_result}")
    print(f"Vector hằng số b_sys = {b_sys}")
    if np.allclose(check_result, b_sys):
        print("Nghiệm được kiểm tra là chính xác.")
    else:
        print("Có sự khác biệt nhỏ giữa nghiệm đã kiểm tra và vector hằng số.")
else:
    print("Không thể kiểm tra nghiệm vì hệ phương trình không được giải bằng phương pháp nghịch đảo ma trận.")

print("\n" + "="*70 + "\n")



Định thức của P = -140.000
Ma trận nghịch đảo của P = 
[[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.05714286  0.2         0.11428571]
 [-0.03571429  0.16428571 -0.05        0.07857143]
 [-0.32142857 -0.12142857 -0.05        0.50714286]]
Định thức của ma trận hệ số A_sys = 14.000
Nghiệm của hệ phương trình (x, y, z, w) = [ -6.         -14.28571429   4.42857143   4.85714286]
A_sys * solution_x = [6. 3. 8. 7.]
Vector hằng số b_sys = [6 3 8 7]
Nghiệm được kiểm tra là chính xác.




In [6]:
#Câu 4: Giá trị riêng, vector riêng và chuẩn hóa
# Cho ma trận Q
Q = np.array([[0, 3, 5],
              [-2, 1, -1],
              [2, 0, 4]])

# a) Tìm các giá trị riêng của Q.
eigenvalues, eigenvectors = np.linalg.eig(Q)
print(f"Các giá trị riêng của Q = {eigenvalues}")

# b) Tìm các vector riêng tương ứng với các giá trị riêng.
# Các cột của eigenvectors là các vector riêng
print(f"Các vector riêng của Q (mỗi cột là một vector riêng): \n{eigenvectors}")

# c) Chuẩn hóa tất cả các vector riêng (độ dài bằng 1). (5 điểm)
normalized_eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
print(f"Các vector riêng đã chuẩn hóa = \n{normalized_eigenvectors}")

print("\n" + "="*70 + "\n")



Các giá trị riêng của Q = [ 5.2862792+0.j         -0.1431396+1.22182766j -0.1431396-1.22182766j]
Các vector riêng của Q (mỗi cột là một vector riêng): 
[[-0.49353583+0.j          0.69251054+0.j          0.69251054-0.j        ]
 [ 0.40931932+0.j          0.47953462+0.43320361j  0.47953462-0.43320361j]
 [-0.76738523+0.j         -0.30754591-0.09069646j -0.30754591+0.09069646j]]
Các vector riêng đã chuẩn hóa = 
[[-0.49353583+0.j          0.69251054+0.j          0.69251054-0.j        ]
 [ 0.40931932+0.j          0.47953462+0.43320361j  0.47953462-0.43320361j]
 [-0.76738523+0.j         -0.30754591-0.09069646j -0.30754591+0.09069646j]]




In [7]:
# Câu 5: Ứng dụng thực tế - Hệ phương trình và phân tích

# Ma trận hệ số R và vector hằng số b
R = np.array([[4, 1, 3],
              [-1, 2, -2],
              [0, 2, 5]])
b_app = np.array([12, 5, 9])

# a) Giải hệ phương trình Rx = b bằng phương pháp np.linalg.solve().
solution_x_app = np.linalg.solve(R, b_app)
print(f"Nghiệm của hệ phương trình (x, y, z) = {solution_x_app}")

# b) Xác định xem ma trận R có khả nghịch không. Nếu có, tính ma trận nghịch đảo và dùng nó để giải lại hệ. So sánh hai nghiệm.
det_R = np.linalg.det(R)
print(f"Định thức của R = {det_R:.3f}")

if det_R == 0:
    print("Ma trận R không khả nghịch vì định thức của nó bằng 0, không thể dùng nghịch đảo để giải hệ.")
else:
    print("Ma trận R khả nghịch.")
    R_inv = np.linalg.inv(R)
    print(f"Ma trận nghịch đảo của R = \n{R_inv}")

    solution_x_inv = np.dot(R_inv, b_app)
    print(f"Nghiệm của hệ phương trình dùng nghịch đảo ma trận = {solution_x_inv}")

    # So sánh hai nghiệm
    if np.allclose(solution_x_app, solution_x_inv):
        print("Hai nghiệm thu được từ hai phương pháp là như nhau (đến một sai số nhỏ).")
    else:
        print("Hai nghiệm thu được từ hai phương pháp có sự khác biệt.")

# c) Tính chuẩn Frobenius của ma trận R.
frobenius_norm_R = np.linalg.norm(R, 'fro')
print(f"Chuẩn Frobenius của ma trận R = {frobenius_norm_R:.3f}")

Nghiệm của hệ phương trình (x, y, z) = [1.83636364 3.72727273 0.30909091]
Định thức của R = 55.000
Ma trận R khả nghịch.
Ma trận nghịch đảo của R = 
[[ 0.25454545  0.01818182 -0.14545455]
 [ 0.09090909  0.36363636  0.09090909]
 [-0.03636364 -0.14545455  0.16363636]]
Nghiệm của hệ phương trình dùng nghịch đảo ma trận = [1.83636364 3.72727273 0.30909091]
Hai nghiệm thu được từ hai phương pháp là như nhau (đến một sai số nhỏ).
Chuẩn Frobenius của ma trận R = 8.000
