<a href="https://colab.research.google.com/github/huvimal/DSTT/blob/main/thithu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Câu 1
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
print("Câu 1a:")
print("A + B =", A + B)
print("3A - 2B =", 3*A - 2*B)

print("\nCâu 1b:")
dot = np.dot(A, B)
angle = np.degrees(np.arccos(dot / (np.linalg.norm(A)*np.linalg.norm(B))))
print("A · B =", dot)
print("Góc =", round(angle, 3), "°")

print("\nCâu 1c:")
C = np.array([[0,3,4],[1,2,-1],[2,-1,0]])
print("Cᵀ × C =\n", np.dot(C.T, C))

# Câu 2
print("\nCâu 2a:")
M = np.array([[1,2,3,0],[4,5,6,1],[7,8,9,2],[0,1,1,0]])
N = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print("M × N =\n", np.dot(M,N))

print("\nCâu 2b:")
try:
    print("det(M) =", np.linalg.det(M))
except:
    print("Không khả thi")

print("\nCâu 2c:")
print("Rank(N) =", np.linalg.matrix_rank(N))

# Câu 3
print("\nCâu 3:")
P = np.array([[2,1,0,1],[0,3,1,4],[1,0,4,2],[0,1,0,3]])
b = np.array([4,7,9,5])
try:
    invP = np.linalg.inv(P)
    print("P⁻¹ =\n", invP)
    x = np.dot(invP, b)
    print("Nghiệm x =", x)
    print("P·x =", np.dot(P,x))
except:
    print("P không khả nghịch")

# Câu 4
print("\nCâu 4:")
Q = np.array([[1,3,4],[-1,0,-2],[0,1,2]])
w, v = np.linalg.eig(Q)
print("Eigenvalues =", w)
print("Eigenvectors =\n", v)
print("Normalized vectors =\n", v / np.linalg.norm(v, axis=0))

# Câu 5
print("\nCâu 5:")
R = np.array([[2,0,1],[1,-2,3],[-1,1,4]])
b5 = np.array([10,8,7])
x5 = np.linalg.solve(R, b5)
print("Giải bằng solve:", x5)
print("R⁻¹ =\n", np.linalg.inv(R))
print("So sánh nghiệm:", np.dot(np.linalg.inv(R), b5))
print("Frobenius norm =", np.linalg.norm(R, 'fro'))


Câu 1a:
A + B = [3 3 1 5]
3A - 2B = [  4 -11  13 -10]

Câu 1b:
A · B = -8
Góc = 108.376 °

Câu 1c:
Cᵀ × C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]

Câu 2a:
M × N =
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

Câu 2b:
det(M) = 6.66133814775094e-16

Câu 2c:
Rank(N) = 2

Câu 3:
P⁻¹ =
 [[ 0.47826087 -0.17391304  0.04347826  0.04347826]
 [ 0.06521739  0.52173913 -0.13043478 -0.63043478]
 [-0.10869565  0.13043478  0.2173913  -0.2826087 ]
 [-0.02173913 -0.17391304  0.04347826  0.54347826]]
Nghiệm x = [ 1.30434783 -0.41304348  1.02173913  1.80434783]
P·x = [4. 7. 9. 5.]

Câu 4:
Eigenvalues = [1.12313309+2.01133917j 1.12313309-2.01133917j 0.75373383+0.j        ]
Eigenvectors =
 [[ 0.78647551+0.j          0.78647551-0.j         -0.5530394 +0.j        ]
 [-0.30476145+0.47219813j -0.30476145-0.47219813j -0.64982438+0.j        ]
 [ 0.25278138+0.04131865j  0.25278138-0.04131865j  0.52141701+0.j        ]]
Normalized vectors =
 [[ 0.78647551+0.j          0.78647551-0.j